[tool.ruff]
line-length = 100
ignore = ["D203"]

[tool.black]
line-length = 100
target-version = ['py311']

[tool.pytest.ini_options]
addopts = "-ra --cov=app"
testpaths = ["tests"]
pythonpath = ['.']
