[tool.ruff]
line-length = 100
ignore = ["D203"]

[tool.black]
line-length = 100
target-version = ['py310']
exclude = '''
(
  ^/testing_code/
)
'''

[tool.pytest.ini_options]
addopts = "-ra --cov=app"
testpaths = ["test"]
pythonpath = ['.']
